CREATE TABLE "job_assignments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "job_assignments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"jobId" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "job_assignments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "job_assignments" ADD CONSTRAINT "job_assignments_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "neon_auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "job_assignments" ADD CONSTRAINT "job_assignments_job_id_job_id_fk" FOREIGN KEY ("jobId") REFERENCES "public"."jobs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE POLICY "admin-authenticated_backend-policy-all" ON "job_assignments" AS PERMISSIVE FOR ALL TO "authenticated_backend" USING (( SELECT (EXISTS ( SELECT 1
           FROM neon_auth."user" u
          WHERE ((u.id = (auth.user_id())::uuid) AND ('admin'::text = ANY (string_to_array(COALESCE(u.role, ''::text), ','::text)))))) AS "exists")) WITH CHECK (( SELECT (EXISTS ( SELECT 1
           FROM neon_auth."user" u
          WHERE ((u.id = (auth.user_id())::uuid) AND ('admin'::text = ANY (string_to_array(COALESCE(u.role, ''::text), ','::text)))))) AS "exists"));--> statement-breakpoint
CREATE POLICY "crud-authenticated_backend-policy-select" ON "job_assignments" AS PERMISSIVE FOR SELECT TO "authenticated_backend" USING (( SELECT ((auth.user_id())::uuid = job_assignments.user_id)));